"""Linux DNS configuration via systemd-resolved or /etc/resolv.conf."""

import shutil
import subprocess
from pathlib import Path

from simurgh_dns.platform_dns.base import DNSSetter

RESOLV_CONF = Path("/etc/resolv.conf")
RESOLV_CONF_BACKUP = Path("/etc/resolv.conf.simurgh-backup")


class LinuxDNSSetter(DNSSetter):
    """DNS setter for Linux using resolvectl or /etc/resolv.conf."""

    def __init__(self) -> None:
        self._use_resolvectl = shutil.which("resolvectl") is not None

    def get_active_interface(self) -> str | None:
        """Detect the active network interface via ip route."""
        try:
            result = subprocess.run(
                ["ip", "route", "get", "1.1.1.1"],
                capture_output=True,
                text=True,
                check=True,
            )
            parts = result.stdout.split()
            if "dev" in parts:
                idx = parts.index("dev")
                return parts[idx + 1]
        except (
            subprocess.CalledProcessError,
            FileNotFoundError,
            IndexError,
        ):
            pass
        return None

    def get_current_dns(self, interface: str) -> list[str]:
        """Get the current DNS servers."""
        if self._use_resolvectl:
            return self._get_dns_resolvectl(interface)
        return self._get_dns_resolv_conf()

    def set_dns(self, interface: str, dns_ips: list[str]) -> bool:
        """Set DNS servers."""
        if self._use_resolvectl:
            return self._set_dns_resolvectl(interface, dns_ips)
        return self._set_dns_resolv_conf(dns_ips)

    def reset_dns(self, interface: str) -> bool:
        """Reset DNS to default."""
        if self._use_resolvectl:
            return self._reset_dns_resolvectl(interface)
        return self._reset_dns_resolv_conf()

    def _get_dns_resolvectl(self, interface: str) -> list[str]:
        try:
            result = subprocess.run(
                ["resolvectl", "dns", interface],
                capture_output=True,
                text=True,
                check=True,
            )
            parts = result.stdout.strip().split(":")
            if len(parts) >= 2:
                servers = parts[-1].strip().split()
                return servers if servers else ["(automatic)"]
            return ["(automatic)"]
        except subprocess.CalledProcessError:
            return ["(unknown)"]

    def _get_dns_resolv_conf(self) -> list[str]:
        try:
            content = RESOLV_CONF.read_text()
            servers = []
            for line in content.split("\n"):
                line = line.strip()
                if line.startswith("nameserver"):
                    parts = line.split()
                    if len(parts) >= 2:
                        servers.append(parts[1])
            return servers if servers else ["(automatic)"]
        except OSError:
            return ["(unknown)"]

    def _set_dns_resolvectl(self, interface: str, dns_ips: list[str]) -> bool:
        try:
            subprocess.run(
                ["sudo", "resolvectl", "dns", interface, *dns_ips],
                check=True,
            )
            return True
        except subprocess.CalledProcessError:
            return False

    def _set_dns_resolv_conf(self, dns_ips: list[str]) -> bool:
        try:
            if RESOLV_CONF.exists() and not RESOLV_CONF_BACKUP.exists():
                subprocess.run(
                    [
                        "sudo",
                        "cp",
                        str(RESOLV_CONF),
                        str(RESOLV_CONF_BACKUP),
                    ],
                    check=True,
                )
            lines = [f"nameserver {ip}" for ip in dns_ips]
            content = "\n".join(["# Generated by simurgh-dns", *lines, ""])
            subprocess.run(
                ["sudo", "tee", str(RESOLV_CONF)],
                input=content,
                text=True,
                check=True,
                capture_output=True,
            )
            return True
        except subprocess.CalledProcessError:
            return False

    def _reset_dns_resolvectl(self, interface: str) -> bool:
        try:
            subprocess.run(
                ["sudo", "resolvectl", "revert", interface],
                check=True,
            )
            return True
        except subprocess.CalledProcessError:
            return False

    def _reset_dns_resolv_conf(self) -> bool:
        try:
            if RESOLV_CONF_BACKUP.exists():
                subprocess.run(
                    [
                        "sudo",
                        "cp",
                        str(RESOLV_CONF_BACKUP),
                        str(RESOLV_CONF),
                    ],
                    check=True,
                )
                subprocess.run(
                    ["sudo", "rm", str(RESOLV_CONF_BACKUP)],
                    check=True,
                )
                return True
            return False
        except subprocess.CalledProcessError:
            return False
